export const config = {
    apiKey: "",
    vault: "",
    protocol: "https://127.0.0.1:27124",
    customPort: false,
    port: "27124",
    liveSearch: true,
    showInPageIcon: true,
    minChars: 2,
    contextLength: 50,
    matchCount: 2,
    noteNumber: 10,
    searchUrls: 'google.com,duckduckgo.com,bing.com,startpage.com,google.at',
    excludes: 'Assets,Template,.excalidraw',
    status: 'offline',
    results: 0,
    searchString: '',

    status: "offline",
    statusText: "❗ Make sure Obsidian is running and set your Protocol settings to connect to your Obsidian REST Api!",
    results: " ",
    color: "gray",
};